from pydantic_settings import BaseSettings
from functools import lru_cache

class Settings(BaseSettings):
    # MongoDB settings
    mongo_uri: str = "mongodb://localhost:27017"
    mongodb_db_name: str = "llm_chat_db"
    
    # API settings
    api_host: str = "0.0.0.0"
    api_port: int = 8000
    
    # Ollama settings
    ollama_base_url: str = "http://localhost:11434"
    
    # Environment
    env: str = "development"

    class Config:
        env_file = ".env"
        case_sensitive = False

@lru_cache()
def get_settings() -> Settings:
    return Settings()

# Generated by Copilot