from fastapi import APIRouter
from typing import List
from app.controllers.model_controller import ModelController
from app.models.model_schemas import ModelInfo, ChatRequest, ChatResponse

router = APIRouter()

@router.get("/models", response_model=List[ModelInfo])
async def get_models():
    return await ModelController.get_all_models()

@router.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    return await ModelController.chat(request.model, request.prompt)

# Generated by Copilot
