from fastapi import APIRouter
from typing import List
from app.controllers.model_controller import ModelController, ModelInfo

router = APIRouter()

@router.get("/models", response_model=List[ModelInfo])
async def get_models():
    return await ModelController.get_all_models()

# Generated by Copilot
