import requests
from typing import List, Dict

class OllamaService:
    def __init__(self, base_url: str = "http://localhost:11434"):
        self._base_url = base_url

    async def list_models(self) -> List[Dict]:
        """Fetch all available models from Ollama"""
        try:
            response = requests.get(f"{self._base_url}/api/tags")
            if response.status_code == 200:
                return response.json().get('models', [])
            return []
        except Exception as e:
            print(f"Error fetching models: {e}")
            return []

# Generated by Copilot
