from app.models.message import Message, MessageResponse

class ChatController:
    @staticmethod
    async def process_message(message: Message) -> MessageResponse:
        # Dummy response for testing
        return MessageResponse(
            message=f"Received your message: {message.content}"
        )

# Generated by Copilot
