from app.services.ollama_service import OllamaService

class ModelController:
    def __init__(self):
        self._ollama_service = OllamaService()

    async def get_available_models(self):
        """Get list of available models"""
        models = await self._ollama_service.list_models()
        return {"models": models}

# Generated by Copilot
