from fastapi import APIRouter
from app.models.message import Message, MessageResponse
from app.controllers.chat_controller import ChatController

router = APIRouter(prefix="/api/chat", tags=["chat"])

@router.post("/message", response_model=MessageResponse)
async def send_message(message: Message):
    return await ChatController.process_message(message)

@router.get("/health")
async def health_check():
    return {"status": "healthy"}

@router.get("/test")
async def test_endpoint():
    return {"message": "API is working correctly!"}

# Generated by Copilot
