from fastapi import APIRouter
from app.controllers.model_controller import ModelController

router = APIRouter(prefix="/api/models", tags=["models"])
model_controller = ModelController()

@router.get("/")
async def list_models():
    """Get all available models"""
    return await model_controller.get_available_models()

# Generated by Copilot
