#!/bin/bash

# Base URL
BASE_URL="http://localhost:8000/api"

echo "1. Testing Get All Models"
curl -s -X GET "${BASE_URL}/models" -H "accept: application/json" | json_pp

echo -e "\n\n2. Creating a new chat thread"
RESPONSE=$(curl -s -X POST "${BASE_URL}/chat" \
  -H "Content-Type: application/json" \
  -d '{
    "message": "What is machine learning?",
    "model": "llama2",
    "user_id": "user123"
  }')
echo "$RESPONSE" | json_pp

# Extract thread ID
THREAD_ID=$(echo "$RESPONSE" | grep -o '"id":"[^"]*' | cut -d'"' -f4)
echo -e "\nExtracted Thread ID: $THREAD_ID"

echo -e "\n\n3. Continue the chat thread"
curl -s -X POST "${BASE_URL}/chat" \
  -H "Content-Type: application/json" \
  -d '{
    "thread_id": "'$THREAD_ID'",
    "message": "Can you provide some examples of machine learning applications?",
    "model": "llama2",
    "user_id": "user123"
  }' | json_pp

echo -e "\n\n4. Get all chat threads"
curl -s -X GET "${BASE_URL}/chat/threads" -H "accept: application/json" | json_pp

echo -e "\n\n5. Get specific chat thread"
curl -s -X GET "${BASE_URL}/chat/thread/$THREAD_ID" -H "accept: application/json" | json_pp

# Uncomment to test delete
# echo -e "\n\n6. Delete chat thread"
# curl -s -X DELETE "${BASE_URL}/chat/thread/$THREAD_ID" -H "accept: application/json" | json_pp

echo -e "\n\nTests completed"

# Generated by Copilot
# Get list of available models
curl -X GET "http://localhost:8000/api/models" -H "accept: application/json"