from typing import List
from pydantic import BaseModel

class ModelDetails(BaseModel):
    parent_model: str
    format: str
    family: str
    families: List[str]
    parameter_size: str
    quantization_level: str

class ModelInfo(BaseModel):
    name: str
    model: str
    modified_at: str
    size: int
    digest: str
    details: ModelDetails

class ChatRequest(BaseModel):
    model: str
    prompt: str

class ChatResponse(BaseModel):
    response: str
    model: str

# Generated by Copilot
